# .goreleaser.linux.yaml
version: 2

project_name: go4wol

before:
  hooks:
    - go mod tidy

builds:
  - id: default
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64

  - id: linux_arm64
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
    goos:
      - linux
    goarch:
      - arm64

  - id: linux_armv7
    env:
      - CGO_ENABLED=1
      - CC=arm-linux-gnueabihf-gcc
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 7

  - id: windows
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
    goos:
      - windows
    goarch:
      - amd64

archives:
  - formats: [tar.gz]
    # 为 windows 创建 zip 存档
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: 'checksums-linux.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: Kaiyuan
    name: go4wol
    mode: replace
